@include('layouts.header')
@yield('main-content')
{{-- <!-- @stack('push_script') --> --}}
@include('layouts.footer')
@include('common.message')
@include('common.form-validation')
@include('common.common_js')
@stack('title')
@stack('custom_css')
@stack('script')
